In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import nltk
import re
import string
import Sastrawi
from nltk.tokenize import word_tokenize
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [2]:
data = pd.read_csv('Twitter_emotion_Dataset.csv')

In [3]:
data

label                                              tweet
0       anger  Soal jln Jatibaru,polisi tdk bs GERTAK gubernu...
1       anger  Sesama cewe lho (kayaknya), harusnya bisa lebi...
2       happy  Kepingin gudeg mbarek Bu hj. Amad Foto dari go...
3       anger  Jln Jatibaru,bagian dari wilayah Tn Abang.Peng...
4       happy  Sharing pengalaman aja, kemarin jam 18.00 bata...
...       ...                                                ...
4396     love  Tahukah kamu, bahwa saat itu papa memejamkan m...
4397     fear  Sulitnya menetapkan Calon Wapresnya Jokowi di ...
4398    anger  5. masa depannya nggak jelas. lha iya, gimana ...
4399    happy  [USERNAME] dulu beneran ada mahasiswa Teknik U...
4400  sadness  Ya Allah, hanya Engkau yang mengetahui rasa sa...

[4401 rows x 2 columns]

In [4]:
data.duplicated().sum()

11

In [5]:
data.drop_duplicates()

label                                              tweet
0       anger  Soal jln Jatibaru,polisi tdk bs GERTAK gubernu...
1       anger  Sesama cewe lho (kayaknya), harusnya bisa lebi...
2       happy  Kepingin gudeg mbarek Bu hj. Amad Foto dari go...
3       anger  Jln Jatibaru,bagian dari wilayah Tn Abang.Peng...
4       happy  Sharing pengalaman aja, kemarin jam 18.00 bata...
...       ...                                                ...
4396     love  Tahukah kamu, bahwa saat itu papa memejamkan m...
4397     fear  Sulitnya menetapkan Calon Wapresnya Jokowi di ...
4398    anger  5. masa depannya nggak jelas. lha iya, gimana ...
4399    happy  [USERNAME] dulu beneran ada mahasiswa Teknik U...
4400  sadness  Ya Allah, hanya Engkau yang mengetahui rasa sa...

[4390 rows x 2 columns]

In [6]:
data['tweet'] = data['tweet'].apply(lambda tweet: ' '.join(word for word in tweet.split() if not word.startswith('[USERNAME]')))
data['tweet'] = data['tweet'].apply(lambda tweet: ' '.join(word for word in tweet.split() if not word.startswith('#')))
data['tweet'] = data['tweet'].apply(lambda tweet: ' '.join(word for word in tweet.split() if not word.startswith('[LINK]')))

In [7]:
data

label                                              tweet
0       anger  Soal jln Jatibaru,polisi tdk bs GERTAK gubernu...
1       anger  Sesama cewe lho (kayaknya), harusnya bisa lebi...
2       happy  Kepingin gudeg mbarek Bu hj. Amad Foto dari go...
3       anger  Jln Jatibaru,bagian dari wilayah Tn Abang.Peng...
4       happy  Sharing pengalaman aja, kemarin jam 18.00 bata...
...       ...                                                ...
4396     love  Tahukah kamu, bahwa saat itu papa memejamkan m...
4397     fear  Sulitnya menetapkan Calon Wapresnya Jokowi di ...
4398    anger  5. masa depannya nggak jelas. lha iya, gimana ...
4399    happy  dulu beneran ada mahasiswa Teknik UI nembak pa...
4400  sadness  Ya Allah, hanya Engkau yang mengetahui rasa sa...

[4401 rows x 2 columns]

In [8]:
def casefold(comment):
    comment = comment.lower()
    comment = re.sub(r':', '', comment)
    comment = re.sub(r'[0-9]+', '', comment)
    comment = re.sub(r'\b[a-zA-Z]\b', '', comment)
    comment = comment.encode('ascii', 'replace').decode('ascii')
    comment = comment.translate(str.maketrans(string.punctuation, ' '*len(string.punctuation)))
    comment = comment.split()
    comment = ' '.join(comment)
    return comment

In [9]:
data['tweet'] = data['tweet'].apply(casefold)

In [10]:
data

label                                              tweet
0       anger  soal jln jatibaru polisi tdk bs gertak gubernu...
1       anger  sesama cewe lho kayaknya harusnya bisa lebih r...
2       happy  kepingin gudeg mbarek bu hj amad foto dari goo...
3       anger  jln jatibaru bagian dari wilayah tn abang peng...
4       happy  sharing pengalaman aja kemarin jam batalin tik...
...       ...                                                ...
4396     love  tahukah kamu bahwa saat itu papa memejamkan ma...
4397     fear  sulitnya menetapkan calon wapresnya jokowi di ...
4398    anger  masa depannya nggak jelas lha iya gimana mau j...
4399    happy  dulu beneran ada mahasiswa teknik ui nembak pa...
4400  sadness  ya allah hanya engkau yang mengetahui rasa sak...

[4401 rows x 2 columns]

In [11]:
data['tweet'] = data['tweet'].apply(word_tokenize)

In [12]:
data

label                                              tweet
0       anger  [soal, jln, jatibaru, polisi, tdk, bs, gertak,...
1       anger  [sesama, cewe, lho, kayaknya, harusnya, bisa, ...
2       happy  [kepingin, gudeg, mbarek, bu, hj, amad, foto, ...
3       anger  [jln, jatibaru, bagian, dari, wilayah, tn, aba...
4       happy  [sharing, pengalaman, aja, kemarin, jam, batal...
...       ...                                                ...
4396     love  [tahukah, kamu, bahwa, saat, itu, papa, memeja...
4397     fear  [sulitnya, menetapkan, calon, wapresnya, jokow...
4398    anger  [masa, depannya, nggak, jelas, lha, iya, giman...
4399    happy  [dulu, beneran, ada, mahasiswa, teknik, ui, ne...
4400  sadness  [ya, allah, hanya, engkau, yang, mengetahui, r...

[4401 rows x 2 columns]

In [13]:
def filtering(comment):
    factory = StopWordRemoverFactory()
    stopword = factory.create_stop_word_remover()
    return stopword.remove(' '.join(comment)).split()

In [14]:
data['tweet'] = data['tweet'].apply(filtering)

In [15]:
data

label                                              tweet
0       anger  [soal, jln, jatibaru, polisi, tdk, bs, gertak,...
1       anger  [sesama, cewe, lho, kayaknya, harusnya, lebih,...
2       happy  [kepingin, gudeg, mbarek, bu, hj, amad, foto, ...
3       anger  [jln, jatibaru, bagian, wilayah, tn, abang, pe...
4       happy  [sharing, pengalaman, aja, kemarin, jam, batal...
...       ...                                                ...
4396     love  [tahukah, kamu, saat, papa, memejamkan, matany...
4397     fear  [sulitnya, menetapkan, calon, wapresnya, jokow...
4398    anger  [masa, depannya, jelas, lha, iya, gimana, mau,...
4399    happy  [dulu, beneran, mahasiswa, teknik, ui, nembak,...
4400  sadness  [allah, engkau, mengetahui, rasa, sakit, hati,...

[4401 rows x 2 columns]

In [16]:
def stemming(text):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    return ' '.join([stemmer.stem(comment) for comment in text])

In [19]:
data['tweet'] = data['tweet'].apply(stemming)

In [21]:
data.to_csv('emotion_after_stemming.csv')

In [68]:
import numpy as np

class CustomTfidfVectorizer:
    def __init__(self):
        self.vocab = {}
        self.idf = {}
        self.doc_count = 0

    def fit(self, corpus):
        doc_term_freqs = []
        for doc in corpus:
            term_freqs = {}
            for term in doc.split():
                if term in term_freqs:
                    term_freqs[term] += 1
                else:
                    term_freqs[term] = 1
            doc_term_freqs.append(term_freqs)
            self.doc_count += 1

            for term in term_freqs:
                if term not in self.vocab:
                    self.vocab[term] = len(self.vocab)

        for term in self.vocab:
            doc_freq = sum(1 for doc in doc_term_freqs if term in doc)
            self.idf[term] = np.log(self.doc_count / (doc_freq + 1)) + 1  # Add 1 to avoid division by zero

    def transform(self, corpus):
        rows = []
        cols = []
        values = []

        for i, doc in enumerate(corpus):
            term_freqs = {}
            for term in doc.split():
                if term in term_freqs:
                    term_freqs[term] += 1
                else:
                    term_freqs[term] = 1
            doc_length = sum(term_freqs.values())

            for term, freq in term_freqs.items():
                if term in self.vocab:
                    rows.append(i)
                    cols.append(self.vocab[term])
                    tfidf = (freq / doc_length) * self.idf[term]
                    values.append(tfidf)

        matrix = np.zeros((len(corpus), len(self.vocab)))
        for row, col, value in zip(rows, cols, values):
            matrix[row, col] = value
        return matrix / np.linalg.norm(matrix, axis=1, keepdims=True)  # Normalize rows to unit Euclidean length

# Usage
documents = data['tweet']
vectorizer = CustomTfidfVectorizer()
vectorizer.fit(documents)
tfidf_matrix = vectorizer.transform(documents)
print(tfidf_matrix)


[[0.35601416 0.18318697 0.20776584 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.21815414 0.21815414 0.21815414]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [69]:

# Melihat rentang nilai dalam tfidf_matrix
min_value = np.min(tfidf_matrix)
max_value = np.max(tfidf_matrix)

print("Rentang nilai dalam tfidf_matrix:")
print("Nilai Minimum:", min_value)
print("Nilai Maksimum:", max_value)


Rentang nilai dalam tfidf_matrix:
Nilai Minimum: 0.0
Nilai Maksimum: 0.9455170483220452


In [34]:
import numpy as np

def train_test_split(x, y, test_size=0.2, random_state=None):
    if random_state is not None:
        np.random.seed(random_state)
    indices = np.random.permutation(len(x))
    split_index = int(len(x) * (1 - test_size))
    return x[indices[:split_index]], x[indices[split_index:]], y.iloc[indices[:split_index]], y.iloc[indices[split_index:]] 


In [37]:
from sklearn.preprocessing import LabelEncoder

# Assuming data['label'] contains your target labels
# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the labels
data['label'] = label_encoder.fit_transform(data['label'])

# You can now use 'encoded_labels' in your analysis


In [38]:
data['label'].value_counts()

label
0    1101
2    1017
4     997
1     649
3     637
Name: count, dtype: int64

In [59]:
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix, data['label'], test_size=0.2, random_state=0)

print(X_train.shape)
print(X_test.shape)
print(len(y_train))
print(len(y_test))

(3520, 13408)
(881, 13408)
3520
881


In [36]:
data['label'].value_counts()

label
anger      1101
happy      1017
sadness     997
fear        649
love        637
Name: count, dtype: int64

In [60]:
import numpy as np

class CustomKNNClassifier:
    def __init__(self, k):
        self.k = k

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def predict(self, X_test):
        y_pred = []
        for x in X_test:
            distances = np.sqrt(np.sum((self.X_train - x) ** 2, axis=1))  # Euclidean distance
            nearest_neighbors = np.argsort(distances)[:self.k]  # Indices of k nearest neighbors
            nearest_labels = self.y_train[nearest_neighbors]  # Labels of k nearest neighbors
            unique_labels, counts = np.unique(nearest_labels, return_counts=True)
            predicted_label = unique_labels[np.argmax(counts)]
            y_pred.append(predicted_label)
        return np.array(y_pred)

In [61]:
y_test.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)

In [62]:
knn = CustomKNNClassifier(k=6)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
y_pred

array([1, 1, 3, 1, 1, 3, 1, 4, 3, 0, 3, 1, 1, 0, 0, 0, 1, 1, 3, 0, 3, 1,
       3, 4, 1, 1, 1, 1, 4, 0, 4, 2, 0, 4, 0, 3, 0, 1, 4, 2, 0, 2, 0, 4,
       3, 3, 1, 4, 0, 0, 0, 0, 3, 0, 0, 2, 4, 0, 1, 0, 1, 1, 1, 0, 0, 2,
       0, 4, 2, 0, 3, 0, 4, 3, 0, 2, 3, 0, 3, 0, 0, 1, 0, 4, 0, 3, 1, 3,
       4, 0, 0, 1, 2, 1, 0, 4, 3, 2, 2, 1, 3, 0, 0, 0, 3, 1, 0, 3, 1, 4,
       0, 0, 2, 4, 3, 1, 3, 2, 3, 3, 0, 0, 0, 2, 2, 2, 1, 3, 0, 3, 0, 0,
       0, 2, 3, 2, 3, 4, 3, 0, 2, 0, 0, 1, 1, 3, 0, 0, 0, 0, 0, 2, 0, 1,
       0, 2, 4, 1, 0, 0, 2, 0, 0, 1, 1, 2, 4, 1, 3, 2, 2, 0, 2, 0, 3, 4,
       4, 1, 1, 1, 0, 3, 0, 3, 3, 4, 4, 2, 0, 1, 1, 0, 1, 3, 1, 2, 4, 1,
       4, 2, 2, 4, 4, 0, 3, 0, 2, 4, 2, 4, 0, 3, 0, 2, 0, 0, 1, 0, 0, 2,
       0, 1, 3, 3, 3, 2, 0, 2, 0, 1, 0, 2, 3, 0, 0, 0, 0, 3, 3, 2, 4, 2,
       2, 3, 0, 0, 0, 0, 0, 2, 2, 4, 0, 2, 1, 1, 1, 4, 2, 0, 4, 4, 2, 4,
       0, 2, 4, 0, 0, 4, 2, 4, 3, 0, 0, 2, 0, 0, 4, 3, 0, 4, 1, 0, 1, 2,
       0, 1, 2, 0, 4, 0, 0, 0, 0, 2, 4, 2, 1, 4, 3,

In [52]:
y_pred1 = knn.predict(X_train)
y_pred1

array([3, 0, 4, ..., 3, 4, 1])

In [63]:
def accuracy(y_pred, y_true):
    return np.mean(y_pred == y_true)


def confusion_matrix(y_true, y_pred):
    classes = np.unique(np.concatenate((y_true, y_pred)))
    matrix = np.zeros((len(classes), len(classes)), dtype=int)
    for i in range(len(y_true)):
        matrix[y_true[i]][y_pred[i]] += 1
    return matrix

print(accuracy(y_pred, y_test))
print(confusion_matrix(y_pred, y_test))

0.49035187287173665
[[126  39  51  13  53]
 [ 20  62  19   8  25]
 [ 15  11  85  14  30]
 [  6  16  26  95  34]
 [ 19  16  27   7  64]]
